# Generated by Django 5.1.1 on 2024-09-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('module_1', models.URLField()),
                ('module_2', models.URLField(blank=True, null=True)),
                ('module_3', models.URLField(blank=True, null=True)),
                ('module_4', models.URLField(blank=True, null=True)),
                ('module_5', models.URLField(blank=True, null=True)),
                ('module_6', models.URLField(blank=True, null=True)),
                ('module_7', models.URLField(blank=True, null=True)),
                ('module_8', models.URLField(blank=True, null=True)),
                ('module_9', models.URLField(blank=True, null=True)),
                ('module_10', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
            ],
        ),
    ]
