# Generated by Django 5.1.1 on 2024-09-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
    ]
