# Generated by Django 5.1.1 on 2024-09-28 03:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
