# Generated by Django 5.1.1 on 2024-09-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_quiz_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
